// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servicios_Prestamos.Server;

#nullable disable

namespace Servicios_Prestamos.Server.Migrations
{
    [DbContext(typeof(BdContexto))]
    [Migration("20230530031856_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Servicios_Prestamos.Shared.Modelos.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<DateTime>("Fecha_Pago")
                        .HasColumnType("datetime2");

                    b.Property<int>("Monto_Pago")
                        .HasColumnType("int");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<int?>("Solicitud_PrestamoSolicitudId")
                        .HasColumnType("int");

                    b.HasKey("PagoId");

                    b.HasIndex("Solicitud_PrestamoSolicitudId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Servicios_Prestamos.Shared.Modelos.Solicitud_Prestamo", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudId"));

                    b.Property<bool>("Estado_Solicitud")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha_Solicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("Monto_Prestamo")
                        .HasColumnType("int");

                    b.Property<int>("Plazo_meses")
                        .HasColumnType("int");

                    b.Property<int>("Tasa_Interes")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("Servicios_Prestamos.Shared.Modelos.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Servicios_Prestamos.Shared.Modelos.Pago", b =>
                {
                    b.HasOne("Servicios_Prestamos.Shared.Modelos.Solicitud_Prestamo", "Solicitud_Prestamo")
                        .WithMany("Pagos")
                        .HasForeignKey("Solicitud_PrestamoSolicitudId");

                    b.Navigation("Solicitud_Prestamo");
                });

            modelBuilder.Entity("Servicios_Prestamos.Shared.Modelos.Solicitud_Prestamo", b =>
                {
                    b.HasOne("Servicios_Prestamos.Shared.Modelos.Usuario", "Usuario")
                        .WithMany("Solicitudes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Servicios_Prestamos.Shared.Modelos.Solicitud_Prestamo", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Servicios_Prestamos.Shared.Modelos.Usuario", b =>
                {
                    b.Navigation("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
